apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-ocp-e2e
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: es-ocp-e2e
        env:
        - name: ENVIRONMENT
          value: staging
        - name: LOG_LEVEL
          value: DEBUG
