# Resource Quota for es-ocp-e2e namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: es-ocp-e2e-quota
  namespace: es-ocp-e2e
  labels:
    app.kubernetes.io/name: es-ocp-e2e
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "64Gi"
    limits.cpu: "40"
    limits.memory: "128Gi"
    persistentvolumeclaims: "20"
    requests.storage: "2Ti"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: es-ocp-e2e-limits
  namespace: es-ocp-e2e
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      max:
        cpu: "8"
        memory: "32Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
