apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - local-path-provisioner.yaml
  - storageclasses.yaml
  - network-policy.yaml
  - network-policy-allow-dns.yaml
  - network-policy-allow-intra-namespace.yaml
  # Uncomment to enable kube-metrics-server:
  #  - ../platform/metrics-server
  # Uncomment to enable OTel Collector (deploy via es-08-observability Kustomization):
  #  - ../observability/otel-collector
