apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-aks-e2e
spec:
  template:
    spec:
      containers:
      - name: es-aks-e2e
        env:
        - name: ENVIRONMENT
          value: development
        - name: DEBUG
          value: "true"
