#!/usr/bin/env python3
"""
ArgoCD deployment addon for project-initializer.
Generates ArgoCD AppProject + component Applications + bootstrap scripts.

Zero external dependencies -- Python 3.9+ stdlib only.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


ADDON_META = {
    "name": "argo_deployment",
    "version": "1.1",
    "description": "ArgoCD GitOps deployment generator",
    "triggers": {"gitops_tool": "argo"},
    "priority": 10,
}


class ArgoDeploymentGenerator:
    """Generates ArgoCD manifests for GitOps deployments."""

    def __init__(
        self,
        project_name: str,
        project_description: str,
        context: Optional[Dict[str, Any]] = None,
    ):
        self.project_name = project_name
        self.description = project_description
        self.context = context or {}

        self.platform = (self.context.get("platform") or "kubernetes").lower()
        self.repo_url = self.context.get("repo_url", f"https://github.com/your-org/{project_name}.git")
        self.target_revision = self.context.get("target_revision", "main")
        self.git_token = (self.context.get("git_token") or "").strip()

        self.cluster_name = (self.context.get("cluster_name") or self.project_name).strip() or self.project_name
        self.domain = (self.context.get("domain") or "{{domain}}").strip() or "{{domain}}"

        sizing_context = self.context.get("sizing_context") or {}
        self.eck_enabled = bool(
            sizing_context
            and (
                sizing_context.get("eck_operator")
                or sizing_context.get("source") == "sizing_report"
            )
        )

    def generate(self) -> Dict[str, str]:
        files: Dict[str, str] = {}

        # ArgoCD control-plane/project resources
        files["argocd/namespace.yaml"] = self._generate_namespace()
        files["argocd/appproject.yaml"] = self._generate_appproject()
        files["argocd/ingress.yaml"] = self._generate_ingress()
        files["argocd/apps/root-app.yaml"] = self._generate_root_app()
        files["argocd/kustomization.yaml"] = self._generate_argocd_kustomization()

        # Component Applications (app-of-apps children)
        for component, path, sync_wave in self._component_apps():
            files[f"argocd/apps/components/{component}.yaml"] = self._generate_component_app(
                component=component,
                path=path,
                sync_wave=sync_wave,
            )

        # Infrastructure scaffold that Flux previously generated by default.
        # Needed for Argo-only projects so component paths are valid.
        files.update(self._generate_infrastructure_scaffold())

        files["argocd/README.md"] = self._generate_readme()
        files["scripts/bootstrap-argocd.sh"] = self._generate_bootstrap_script()
        files["scripts/argocd-sync.sh"] = self._generate_sync_script()
        return files

    def _component_apps(self) -> List[Tuple[str, str, str]]:
        components: List[Tuple[str, str, str]] = [
            ("infrastructure", "infrastructure", "0"),
            ("elasticsearch", "elasticsearch", "1"),
            ("kibana", "kibana", "2"),
        ]
        if self.eck_enabled:
            components.append(("agents", "agents", "3"))
        return components

    def _argocd_host(self) -> str:
        return f"argocd.{self.cluster_name}.{self.domain}"

    def _generate_namespace(self) -> str:
        return """apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
"""

    def _generate_appproject(self) -> str:
        return f"""apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {self.project_name}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "{self.description}"
  sourceRepos:
    - "{self.repo_url}"
  destinations:
    - namespace: "{self.project_name}"
      server: "https://kubernetes.default.svc"
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
    - namespace: "observability"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
"""

    def _generate_root_app(self) -> str:
        return f"""apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {self.project_name}-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {self.project_name}
  source:
    repoURL: "{self.repo_url}"
    targetRevision: {self.target_revision}
    path: argocd/apps/components
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
"""

    def _generate_component_app(self, component: str, path: str, sync_wave: str) -> str:
        return f"""apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {self.project_name}-{component}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{sync_wave}"
spec:
  project: {self.project_name}
  source:
    repoURL: "{self.repo_url}"
    targetRevision: {self.target_revision}
    path: {path}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {self.project_name}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
"""

    def _generate_ingress(self) -> str:
        host = self._argocd_host()
        return f"""apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {host}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
"""

    def _generate_argocd_kustomization(self) -> str:
        return """apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - appproject.yaml
  - ingress.yaml
  - apps/root-app.yaml
"""

    def _generate_infrastructure_scaffold(self) -> Dict[str, str]:
        infra_resources = [
            "namespace.yaml",
            "local-path-provisioner.yaml",
            "storageclasses.yaml",
            "network-policy.yaml",
            "network-policy-allow-dns.yaml",
            "network-policy-allow-intra-namespace.yaml",
            "network-policy-allow-eck-operator.yaml",
            "network-policy-allow-ingress-nginx.yaml",
            "network-policy-allow-kibana-egress.yaml",
            "network-policy-allow-agent-egress.yaml",
        ]

        files: Dict[str, str] = {
            "infrastructure/README.md": """# Shared Infrastructure Components

Managed by ArgoCD (component app: infrastructure).
""",
            "infrastructure/kustomization.yaml": (
                "apiVersion: kustomize.config.k8s.io/v1beta1\n"
                "kind: Kustomization\n"
                "resources:\n"
                + "\n".join([f"  - {r}" for r in infra_resources])
                + "\n"
                "  - ../platform/eck-operator\n"
            ),
            "infrastructure/namespace.yaml": f"""apiVersion: v1
kind: Namespace
metadata:
  name: {self.project_name}
  labels:
    project: {self.project_name}
""",
            "infrastructure/network-policy.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-default-deny
  namespace: {self.project_name}
spec:
  podSelector: {{}}
  policyTypes:
  - Ingress
  - Egress
""",
            "infrastructure/network-policy-allow-dns.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-allow-dns
  namespace: {self.project_name}
spec:
  podSelector: {{}}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
""",
            "infrastructure/network-policy-allow-intra-namespace.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-allow-intra-namespace
  namespace: {self.project_name}
spec:
  podSelector: {{}}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {{}}
  egress:
  - to:
    - podSelector: {{}}
    - ipBlock:
        cidr: 0.0.0.0/0
""",
            "infrastructure/network-policy-allow-eck-operator.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-allow-eck-operator
  namespace: {self.project_name}
spec:
  podSelector: {{}}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: elastic-system
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: elastic-system
""",
            "infrastructure/network-policy-allow-ingress-nginx.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-allow-ingress-nginx
  namespace: {self.project_name}
spec:
  podSelector: {{}}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 5601
""",
            "infrastructure/network-policy-allow-kibana-egress.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-allow-kibana-egress
  namespace: {self.project_name}
spec:
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 9200
""",
            "infrastructure/network-policy-allow-agent-egress.yaml": f"""apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {self.project_name}-allow-agent-egress
  namespace: {self.project_name}
spec:
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: agent
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 6443
    - protocol: TCP
      port: 9200
    - protocol: TCP
      port: 8220
""",
            "infrastructure/storageclasses.yaml": """apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
""",
            "infrastructure/local-path-provisioner.yaml": Path(__file__).resolve().parent.joinpath(
                "assets", "infrastructure", "local-path-provisioner.yaml"
            ).read_text(),
        }
        return files

    def _generate_bootstrap_script(self) -> str:
        return f"""#!/usr/bin/env bash
set -euo pipefail

PROJECT_NAME=\"{self.project_name}\"
ROOT_DIR=\"$(cd \"$(dirname \"$0\")/..\" && pwd)\"
TARGET_REVISION=\"{self.target_revision}\"
REPO_URL=\"{self.repo_url}\"

command -v kubectl >/dev/null 2>&1 || {{ echo >&2 \"kubectl is not installed\"; exit 1; }}

if ! kubectl get namespace argocd >/dev/null 2>&1; then
  kubectl create namespace argocd
fi

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
kubectl -n argocd wait deployment/argocd-server --for=condition=Available --timeout=10m || true

if [[ -n \"{self.git_token}\" ]]; then
  kubectl -n argocd create secret generic \"$PROJECT_NAME-git-auth\" \\
    --from-literal=username=oauth2 \\
    --from-literal=password=\"{self.git_token}\" \\
    --dry-run=client -o yaml | kubectl apply -f -
fi

kubectl apply -f \"$ROOT_DIR/argocd/appproject.yaml\"
kubectl apply -f \"$ROOT_DIR/argocd/apps/root-app.yaml\"
kubectl apply -f \"$ROOT_DIR/argocd/ingress.yaml\" || true

echo \"ArgoCD bootstrap/configuration complete.\"
echo \"UI host: {self._argocd_host()}\"
"""

    def _generate_sync_script(self) -> str:
        return f"""#!/usr/bin/env bash
# ArgoCD sync script for {self.project_name}

set -euo pipefail

APP_NAME=\"{self.project_name}-root\"

echo \"Syncing $APP_NAME...\"

if command -v argocd &> /dev/null; then
    argocd app sync \"$APP_NAME\" --prune || true
    argocd app wait \"$APP_NAME\" --health || true
else
    echo \"ArgoCD CLI not found. Applying root app with kubectl...\"
    kubectl apply -f argocd/apps/root-app.yaml
fi

echo \"Sync complete!\"
"""

    def _generate_readme(self) -> str:
        components = "\n".join(
            [f"- `{self.project_name}-{name}` → `{path}/`" for name, path, _ in self._component_apps()]
        )
        return f"""# ArgoCD Configuration: {self.project_name}

## Overview

ArgoCD app-of-apps setup for this project.

## Component Applications

{components}

## Bootstrap

```bash
bash scripts/bootstrap-argocd.sh
```

## Manual sync

```bash
bash scripts/argocd-sync.sh
```

## ArgoCD UI

- Host: `https://{self._argocd_host()}`
"""


def main(
    project_name: str,
    description: str,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    generator = ArgoDeploymentGenerator(project_name, description, context)
    return generator.generate()


if __name__ == "__main__":
    files = main("test-cluster", "Test Elasticsearch cluster with ArgoCD", {
        "platform": "rke2",
        "gitops_tool": "argo",
        "repo_url": "https://github.com/myorg/test-cluster.git",
    })

    print("Generated files:")
    for filepath in sorted(files.keys()):
        print(f"  - {filepath}")
