apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  template:
    spec:
      containers:
      - name: test-project
        env:
        - name: ENVIRONMENT
          value: development
        - name: DEBUG
          value: "true"
