apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-project
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-org/test-project.git
  ref:
    branch: main
  timeout: 2m
  ignore: |
    # Exclude files from synchronization
    /*.md
    /docs
    /scripts
