apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-ocp-e2e
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: es-ocp-e2e
        env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: INFO
